### ISSUE TITLE
Add rustc_hash to benchmarks

### ISSUE THREAD

**Issue by smmalis37** [tkaitchuck/aHash#102]
https://crates.io/crates/rustc-hash

I'd be curious to see how things compare. Their docs say they outperform FNV, which is promising.

**Comment by tkaitchuck** [comment]
rustc-hash is basically the same as fxHash just with different constants. You can see it in the graph. 
Based on this issue: https://github.com/rust-lang/rustc-hash/pull/18
I have been toying around with an improved version of rustc-hash. When that is ready I will post a PR there and update aHash's fallback with anything I learn. 

Also: "Faster than FNV" isn't saying much, as you can see from the graph here: https://github.com/tkaitchuck/aHash/blob/master/compare/readme.md#speed
FNV is one of the slowest popular hashing algorithms.
