### ISSUE TITLE
Does `AHashMap` really need to be a newtype?

### ISSUE THREAD

**Issue by emilk** [tkaitchuck/aHash#103]
Currently `AHashMap` is defined as:

`pub struct AHashMap<K, V, S = crate::RandomState>(HashMap<K, V, S>);`

It seems to me it could instead have been defined as:

`pub type AHashMap<K, V> = HashMap<K, V, crate::BuildRandomState>;`

This is the approach taken by [`nohash_hasher::IntMap`](https://docs.rs/nohash-hasher/0.2.0/nohash_hasher/type.IntMap.html):

`pub type IntMap<K, V> = HashMap<K, V, BuildNoHashHasher<K>>;`

Having `AHashMap` as a special-case of a `HashMap` would be a boon for any code written to be generic over different types of `HashMap`. Currently such code isn't compatible with `AHashMap`. For instance:

``` rust
fn foo<K, V, S>(map: &HashMap<K, V, S>);`
```

can be called with `nohash_hasher::IntMap`, but not with `ahash::HashMap`.

---

I'm sure there is a good reason for why the code is written as is, but perhaps this could at least be an option?

**Comment by tkaitchuck** [comment]
See the explanation in the description of PR which added it: 
https://github.com/tkaitchuck/aHash/pull/23

If you can see a good way to solve that while preserving type transparency, then by all means an alias would be prefered and I would welcome a PR.

**Comment by emilk** [comment]
Thanks for the explanation @tkaitchuck (in hind-sight I should have looked it up myself).

One alternative is to add `new` and `with_capacity` as trait extensions:

``` rust
trait HashMapExt {
    fn new() -> Self;
    fn with_capacity(x: usize) -> Self;
}

impl<K, V, S> HashMapExt for HashMap<K, V, S>
where
    K: Hash + Eq,
    S: BuildHasher + Default,
{
    fn new() -> Self {
        HashMap::with_hasher(S::default())
    }

    fn with_capacity(capacity: usize) -> Self {
        HashMap::with_capacity_and_hasher(capacity, S::default())
    }
}
```

This would mean users could still use a `AHashMap` typedef as a drop-in replacement for `std::collections::HashMap`, but  would require users to import the trait (`use ahash::HashMapExt as _;`) in order to use `new` and `with_capacity`.

This is not ideal, but it is an alternative worth considering (again, perhaps as a feature-gated option to the current newtype).

---

Interestingly, `AHashMapExt` above is completely agnostic to `ahash`, and would also work with other hashing alternatives (like `nohash_hasher`). It could potentially be added to the standard library and its prelude, though I'm sure there are some good reasons not to do so. I've started a discussion about this at https://internals.rust-lang.org/t/hashmap-set-new-with-capacity-and-buildhasher/15622

**Comment by emilk** [comment]
On a completely separate topic: I love the `ahash` crate. It is awesome :)

**Comment by emilk** [comment]
What do you think about letting users choose between `struct AHashMap(…)` and `type AHashMap = …` with feature flags?

For instance: we could introduce the mutually exclusive feature flags `newtype` and `type-alias`, and have the former as a default feature (for backwards compatibility)? I'd be happy so submit a PR for this.
