### ISSUE TITLE
Hasher is not invariant on small writes with .write vs .write_u8

### ISSUE THREAD

**Issue by theatrus** [tkaitchuck/aHash#108]
Consider the following program:

```
use ahash; // 0.7.6
use std::hash::Hasher;

fn main() {
    let mut hash1 = ahash::AHasher::default();
    let mut hash2 = ahash::AHasher::default();
    
    let input = b"12345".as_ref();
    hash1.write(input);
    for k in input.iter() {
        hash2.write_u8(*k);
    }
    assert_eq!(hash1.finish(), hash2.finish());
}
```

We would assume hash1 and hash2 produce the same value, having the same sequence of bytes written, however the assertion fails.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8d4837e9666e0c75293a387435885200

The assertion passes using the std:: SipHasher

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7d89099aa02615fe5ce5e8065767fcf9

**Comment by theatrus** [comment]
Small sized .write() is also not consistent

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1b56400d019ae6c46bc756e328ad6159

**Comment by theatrus** [comment]
As in aside, wyhash, fxhash are also not immune to this symptom of stretching single or small writes to much larger hash states than intended. The stdlib hasher is the only one so far that gets this correct so far.

A naive buffering-before-flushing hasher would require `fn finish(&mut self)` which isn't directly possible.

**Comment by tkaitchuck** [comment]
This is not a guaranteed property of the Hasher trait. So it is not accurate to refer to this as being "correct". It is simply an additional property which sipHash happens to offer that ahash, wyhash, and fxhash do not. As there are MAJOR performance gains from not supporting this feature, and because it is not required by the trait or by any  hashmap implementation that I am aware of, supporting it is not a priority.

**Comment by schungx** [comment]
Curious question: Why should the two be the same?  I'd actually assume them to be _different_.

One is a slice of five bytes.

One is five consecutive single bytes.

Even the types are different.  Why should they hash to the same thing?

Case in point:  consider:

```rust
struct MyStruct(i32, i32);

let x = MyStruct(1,2);
let y: i64 = 0x0000000100000002;

x.hash() == y.hash() ?
```

The fact that two types have the same byte representation does not mean that they should hash to the same thing...

**Comment by tkaitchuck** [comment]
This is in fact called out _explicetly_ in the final paragraph of the top section here: https://doc.rust-lang.org/std/hash/trait.Hasher.html
