### ISSUE TITLE
Clarify copyright situation

### ISSUE THREAD

**Issue by alexanderkjall** [tkaitchuck/aHash#113]
Amanieu d'Antras is listed as the copyright owner in https://github.com/tkaitchuck/aHash/blob/master/LICENSE-MIT#L1 but isn't mentioned anywhere else.

Would it be possible to clarify the copyright situation, should both Amanieu d'Antras and Tom Kaitchuck be attributed the copyright, or is the LICENSE-MIT file a copy&paste error?

This needs to be clarified when packaging the code for debian.

**Comment by tkaitchuck** [comment]
Yes. It was a copy and paste error. Fixed.
