### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [tkaitchuck/aHash#119]
Please tag releases in git, to help ease correlating with Cargo releases.

**Comment by tkaitchuck** [comment]
I have tagged the latest release in each of the minor versions and will add future tags as versions are released. 
(To correlate older patch versions, look at the branch for the corresponding minor versions and look at the PR where the cargo.toml was updated in it's version. This is the PR that was pushed.)

**Comment by jonassmedegaard** [comment]
Excellent - much appreciated!
