### ISSUE TITLE
Reproducible builds.

### ISSUE THREAD

**Issue by tkaitchuck** [tkaitchuck/aHash#12]
Currently aHash uses const_random to improve performance. However this has the consequences of making the binary produced form a build non-identical. This can be a problem in some cases.

Ideally this should not be the case. Need to identify some mechanism of generating a key that doesn't have this requirement.

**Comment by tkaitchuck** [comment]
Generating a random value using Rand on ever map creation is a problem because of the overhead.

Unlike the standard library implementation, we can't use a thread local counter, because:
1. This requires STD
2. This involves doing a hashMap lookup every time we are creating a hashMap. (Which would inturn pull in siphash and be a huge performance hit)

**Comment by Amanieu** [comment]
You could try using the address of a stack variable. This should be somewhat randomized thanks to ASLR.

**Comment by Amanieu** [comment]
On the other hand, embedded systems without ASLR would be better off with const_random.

**Comment by tkaitchuck** [comment]
@Amanieu 
The code is currently using Const_random to get a default seed and combining this with the address of the hashBuilder to make every map unique. ASLR defiantly makes this better.
I would prefer not to rely solely on the address location, but I don't know any any other good cheap sources of randomness...

**Comment by Amanieu** [comment]
I just had an idea: `const_random!` could check if a `CONST_RANDOM_SEED` environment variable exists and use that as the RNG seed. If no environment variable is set then just use a random seed.

**Comment by tkaitchuck** [comment]
This can now be accomplished by turning off the feature "compile-time-rng"
