### ISSUE TITLE
Consider Re-Exposing `AHasher::new_with_keys`

### ISSUE THREAD

**Issue by joshstoik1** [tkaitchuck/aHash#122]
Hi there,

I might be missing something, but I I can't seem to get `AHasher::default` hashes to agree with each other across `build.rs`/`lib.rs` boundaries. Prior to `0.8.0`, I was able to accomplish this via `AHasher::new_with_keys` using fixed seeds.

For background, I had been generating a lookup table of pre-computed `u64` hashes in `build.rs` that `lib.rs` could reference to answer the question, "Is such and such included?" Moving the computations to runtime works, but there are a gazillion of them, hence the preference to handle the crunching during compiletime. :wink: 

Does `AHasher::new_with_keys` need to be `pub(crate)`?

Thanks!

**Comment by joshstoik1** [comment]
I apologize, I believe `ahash::RandomState::with_seeds` will do the trick. Thanks again for the excellent crate.

**Comment by turalcar** [comment]
The proper way would still be to deprecate it first with properly describing the way to migrate in the comments
