### ISSUE TITLE
Cannot compile to wasm without wasm-bindgen with v0.8.1

### ISSUE THREAD

**Issue by Frazzer951** [tkaitchuck/aHash#140]
In the latest update `getrandom` now includes `wasm-bindgen` which causes problems in my project because I'm just compiling raw WASM.

Is there a way to compile this library for wasm that doesn't force the `js` feature in `getrandom`?

This has also been pointed out at https://github.com/tkaitchuck/aHash/pull/129#issuecomment-1300997933 which is on the pull-request which made the change to cause this issue

**Comment by schungx** [comment]
I agree adding a `js` feature that maps to `getrandom/js` is best.

I used to manually set `getrandom/js` whenever I see `wasm-bindgen` but then the new version now has no way to turn it off.

**Comment by schungx** [comment]
This also causes #141 which breaks `no-std` builds.

**Comment by schungx** [comment]
In fact, the standard `ahash` with `default-features = false` will always bring in `wasm-bindgen` (you can tell by inspecting `Cargo.lock`) and all its dependencies for no apparent reason, all because `getrandom/js` is turned on.

An alternative is to omit the check for `target_abi = "unknown"` since the `target_abi` is not yet stable.

**Comment by schungx** [comment]
https://github.com/rust-lang/cargo/issues/4866  documents the fact that *target-specific* features are not supported.  All features are merged regardless of target.

**Comment by schungx** [comment]
Based on https://github.com/rust-lang/cargo/issues/1197#issuecomment-268203727 there is an alternative solution:

```toml
[dependencies]
getrandom = { version = "0.2.7", optional = true }

[target.'cfg(target_family = "wasm")'.features]
default = ["getrandom/js"]
```

**Comment by tkaitchuck** [comment]
Fixed
