### ISSUE TITLE
0.8.1 fails to compile for no-std

### ISSUE THREAD

**Issue by schungx** [tkaitchuck/aHash#141]
The added feature of `getrandom/js` is breaking `no-std` builds by pulling in `wasm-bindgen` (for no reason).

EDIT: https://github.com/rust-lang/cargo/issues/4866 and https://github.com/rust-lang/cargo/issues/1197 document the fact that target-specific features are not supported. All features are merged regardless of target.

This is an issue in addition to #140.

**Comment by schungx** [comment]
I strong concur with #140 that the best solution is to add a `js` feature which turns on `getrandom/js`.

JavaScript interop is really an external feature outside of core target architecture and O/S, so it is reasonable to assume that it should be specifically specified.

Assuming the existence of JavaScript for all `wasm` and `no-std` targets is simply wrong; since not all warm runs on a browser, and `no-std` most likely doesn't have JavaScript around.

**Comment by tkaitchuck** [comment]
Fixed.
