### ISSUE TITLE
adding ability to build HashMap from rayon parallel iterator

### ISSUE THREAD

**Issue by bobi6666** [tkaitchuck/aHash#147]
hello can you please add ability for HashMap in this crate that allow me to build HashMap from rayon parallel iterator?

**Comment by tkaitchuck** [comment]
Hashmap is just a type alias: https://docs.rs/ahash/0.8.2/ahash/#aliases
So, if it is possible to build a standard hashmap then it should work too. It looks like this should do what you want:
https://docs.rs/rayon/1.6.1/rayon/iter/trait.FromParallelIterator.html#impl-FromParallelIterator%3C(K%2C%20V)%3E-for-HashMap%3CK%2C%20V%2C%20S%3E
