### ISSUE TITLE
Please disable feature `runtime-rng` by default

### ISSUE THREAD

**Issue by sundy-li** [tkaitchuck/aHash#148]
We introduce aHash  in our database system. By default, this crate will generate different hash results in distributed nodes, which is disastrous. 

So I propose disabling the feature `runtime-rng` by default.

**Comment by amab8901** [comment]
why was this issue closed when there are no PR:s that solve the issue?

**Comment by schungx** [comment]
Can you do `default-features = false` to get rid of it?

There is already a way to use `ahash` with fixed seeds in order to guarantee stable hashes.

Therefore I suppose it is close because RTFM.

**Comment by amab8901** [comment]
> Can you do `default-features = false` to get rid of it?
> 
> There is already a way to use `ahash` with fixed seeds in order to guarantee stable hashes.
> 
> Therefore I suppose it is closed because RTFM.

wouldn't it be more appropriate then to label it as "not planned" rather than "closed"? Because "closed" suggests that an actual solution has been implemented in response to the issue (rather than a pre-existing solution making the issue unnecessary)
