### ISSUE TITLE
aHash changed TypeId 

### ISSUE THREAD

**Issue by RuiSiJia** [tkaitchuck/aHash#157]
When I used ahash, I noticed that ahash changed the TypeId of datafusion::arrow::array::StringArray compared to not using ahash. Can someone explain why?

**Comment by tkaitchuck** [comment]
You are referring to this: https://doc.rust-lang.org/stable/std/any/struct.TypeId.html  ?
That should be generated by the compiler, and has nothing to do with aHash unless you mean that you modified the compiler to use aHash internally. 
Though I don't believe that those IDs are guaranteed to be stable, so it could just be a coincidence
