### ISSUE TITLE
const_random should be a build dependency?

### ISSUE THREAD

**Issue by cbeck88** [tkaitchuck/aHash#16]
Hi, I'm trying to cross-compile code that uses hashbrown and ahash to a small system.
I run into trouble because aHash depends on const_random and then ultimately on rand, which I cannot cross-compile because it relies on libc.

I think `const_random` is only providing a macro, so it is only needed at build-time, and only needs to be compiled for the host. Is this correct? If so, can we mark `const_random` as a build dependency instead?

**Comment by Amanieu** [comment]
hashbrown is [tested in CI](https://github.com/rust-lang/hashbrown/blob/master/.travis.yml#L65) to check that it builds on thumbv6m systems. You might be hitting https://github.com/rust-lang/cargo/issues/5730 if another one of your dependencies is using `rand`, and the build-dependency is enabling the `std` feature.

**Comment by cbeck88** [comment]
this doesn't answer my question though --
since const_random is just a proc-macro it should be built for the host architecture, right?
the current configuration seems to mean that rand is compiled for the target architecture

even if that works in hashbrown-ci it seems like this isn't being configured correctly -- we only need rand at build time so either it or one of the links in this chain back to the user should be marked as a build dependency, right?

Here's a portion of my `cargo tree`:

```
│   ├── common v0.1.0 (/root/mobilenode/src/common)
│   │   ├── ahash v0.2.9
│   │   │   ├── const-random v0.1.6
│   │   │   │   ├── const-random-macro v0.1.6
│   │   │   │   │   ├── proc-macro-hack v0.5.8
│   │   │   │   │   │   ├── proc-macro2 v0.4.30
│   │   │   │   │   │   │   └── unicode-xid v0.1.0
│   │   │   │   │   │   ├── quote v0.6.13
│   │   │   │   │   │   │   └── proc-macro2 v0.4.30 (*)
│   │   │   │   │   │   └── syn v0.15.42
│   │   │   │   │   │       ├── proc-macro2 v0.4.30 (*)
│   │   │   │   │   │       ├── quote v0.6.13 (*)
│   │   │   │   │   │       └── unicode-xid v0.1.0 (*)
│   │   │   │   │   └── rand v0.7.0
│   │   │   │   │       ├── getrandom v0.1.8
│   │   │   │   │       │   ├── cfg-if v0.1.9 (*)
│   │   │   │   │       │   └── libc v0.2.60
│   │   │   │   │       ├── libc v0.2.60 (*)
│   │   │   │   │       ├── rand_chacha v0.2.1
│   │   │   │   │       │   ├── c2-chacha v0.2.2
│   │   │   │   │       │   │   ├── lazy_static v1.3.0
│   │   │   │   │       │   │   │   └── spin v0.5.0
│   │   │   │   │       │   │   └── ppv-lite86 v0.2.5
│   │   │   │   │       │   └── rand_core v0.5.0
│   │   │   │   │       │       └── getrandom v0.1.8 (*)
│   │   │   │   │       └── rand_core v0.5.0 (*)
│   │   │   │   │       [dev-dependencies]
```

I think that either `ahash` to `const_random` or `const_random` to `const_random_macro` should be marked as a build dependency, right? I really don't want to compile `rand` for my target if I don't need it, even with limited features.

**Comment by cbeck88** [comment]
@Amanieu in `const_random_macro` Cargo.toml we have this:

https://github.com/tkaitchuck/constrandom/blob/master/macro/Cargo.toml#L17

```
rand = { version = "0.7", default-features = false, features = ["getrandom"] }
```

this isn't gonna work even if `no_std` is there, there is no implementation of `getrandom` on the target

**Comment by Amanieu** [comment]
`const-random-macro` is a proc macro crate, which is always built for the host, even when cross-compiling. All its dependencies are also built for the host.

If you look at your full `cargo tree`, is the `rand` crate used anywhere else?

**Comment by cbeck88** [comment]
@Amanieu I made the following reduced test, and it is working. So I think you are right, sorry for the noise, and thanks for helping me!

```
#!/bin/bash

rm -rf example
cargo new example --lib

cd example

echo "ahash = \"0.2\"" >> Cargo.toml
rm src/lib.rs
echo "#![no_std]
extern crate ahash;" > src/lib.rs

echo "{\
  \"arch\": \"x86_64\",\
  \"cpu\": \"x86-64\",\
  \"data-layout\": \"e-m:e-i64:64-f80:128-n8:16:32:64-S128\",\
  \"dynamic-linking\": true,\
  \"env\": \"sgx\",\
  \"executables\": true,\
  \"has-elf-tls\": true,\
  \"has-rpath\": true,\
  \"is-builtin\": false,\
  \"linker-flavor\": \"gcc\",\
  \"linker-is-gnu\": true,\
  \"llvm-target\": \"x86_64-unknown-linux-gnu\",\
  \"max-atomic-width\": 64,\
  \"os\": \"none\",\
  \"position-independent-executables\": true,\
  \"pre-link-args\": {\
    \"gcc\": [\
      \"-Wl,--as-needed\",\
      \"-Wl,-z,noexecstack\",\
      \"-m64\"\
    ]\
  },\
  \"relro-level\": \"full\",\
  \"stack-probes\": true,\
  \"target-c-int-width\": \"32\",\
  \"target-endian\": \"little\",\
  \"target-family\": \"unix\",\
  \"target-pointer-width\": \"64\",\
  \"vendor\": \"unknown\"\
}" > x86-64-unknown-linux-gnu.json

cargo xbuild --target x86-64-unknown-linux-gnu.json -v
```
