### ISSUE TITLE
Documentation of the fallback algorithm seems to not match the source

### ISSUE THREAD

**Issue by chandlerc** [tkaitchuck/aHash#164]
On the https://github.com/tkaitchuck/aHash/wiki/AHash-fallback-algorithm documentation for the fallback algorithm, I think there is a discrepancy between the code and the document.

The document says:
> Or for larger updates:
> 
> 1) The update is broken into two halves
> 2) Each half is xored with a key.
> 3) They are then "folded multiplied" with each other.
> 4) The another key is added to the result
> 5) It is then xored into the the prior state.
> 6) A fixed rotation is applied to the state.

The code is https://github.com/tkaitchuck/aHash/blob/master/src/fallback_hash.rs#L113-L114 --
```
    fn large_update(&mut self, new_data: u128) {
        let block: [u64; 2] = new_data.convert();
        let combined = folded_multiply(block[0] ^ self.extra_keys[0], block[1] ^ self.extra_keys[1]);
        self.buffer = (self.buffer.wrapping_add(self.pad) ^ combined).rotate_left(ROT);
    }
```

This seems to add *buffer*, the prior state, to the key and then xor that with the result of the folded multiply? I think rewritten, the steps might be:

1) The update is broken into two halves
2) Each half is xored with a key.
3) They are then "folded multiplied" with each other.
4) In parallel, another key is added to the prior state.
5) Then the result of (3) and (4) are xored with each other to form the new state.
6) A fixed rotation is applied to the new state.

Have I missed anything?

**Comment by tkaitchuck** [comment]
Yes, you are correct. The wiki was out of date. I have updated it with the text you have written here.
