### ISSUE TITLE
ahash still doesn't work on no_std for me

### ISSUE THREAD

**Issue by CryZe** [tkaitchuck/aHash#17]
When I try to compile it, it errors with the following errors (repeating for every macro invocation):
```
Compiling ahash v0.2.12
error: cannot find macro `proc_macro_call!` in this scope
  --> C:\Users\Christopher Serr\.cargo\registry\src\github.com-1ecc6299db9ec823\ahash-0.2.12\src/lib.rs:49:45
   |
49 | static SEED: AtomicUsize = AtomicUsize::new(const_random!(u64));
   |                                             ^^^^^^^^^^^^^^^^^^
   |
   = help: have you added the `#[macro_use]` on the module/import?
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by tkaitchuck** [comment]
@CryZe While this looks like an easy fix, I would like to be able to reproduce the problem so I can verify I have fixed it. I have tried several ways to reproduce this and have so far been unable to do so.

What version of rustc are you compiling with? What arch / flags are you using?
Do you have a branch I can check out where the build fails?

**Comment by CryZe** [comment]
mmh, I can't seem to be able to replicate it either. This is very odd. I guess this can be closed and I might reopen it if it happens again and I have some reproducible way to get it to happen.
