### ISSUE TITLE
All 0.7.x versions have been yanked?

### ISSUE THREAD

**Issue by keehun** [tkaitchuck/aHash#174]
Hi @tkaitchuck,

Thank you for this amazing crate. I (and I am sure many others) really appreciate all the work you (and other contributors) have put into this.

This afternoon, it looks like all 0.7.x versions and <=0.8.3 versions (and maybe more) have been yanked? Was this on purpose? Looking at some of the other issues & recent merges, was only 0.8.4 meant to be yanked?

`cbindgen` has `ahash 0.7.6` as a sub-dependency (through `indexmap 1.9.3`), so I wonder if many people will notice the yanked crate versions very soon. I've reported this to `cbindgen` [here](https://github.com/mozilla/cbindgen/issues/893) and now I'm looking to see if I can maybe get `indexmap` updated in `cbindgen` to help this transition if it was intended.

**Comment by Ten0** [comment]
I was about to post this.

Yanking older versions without making fixed semver-compatible versions available broke a bunch of other crates, preventing `cargo update`, CI runs...
Considering how `ahash` is clearly described as "not a cryptographically secure hash", maybe posting these to https://rustsec.org/ rather than yanking would be the best way to handle the security vulnerabilities.

**Comment by keehun** [comment]
Ah, I just saw https://github.com/tkaitchuck/aHash/issues/163. This seems to be on purpose.

**Comment by partisan-bobryk** [comment]
Yea i don't know if Yanking the packages was a good call. Now a significant portion of ecosystem is broken. 🤦‍♂️ This package is 5 levels down. ouef

**Comment by keehun** [comment]
I encourage everyone to not judge whether or not it was a good call but rather discuss how best to help this crate move forward.

**Comment by tkaitchuck** [comment]
Please see here for the reason: https://github.com/tkaitchuck/aHash/wiki/Yanked-versions
I can work on publishing a patch to the 0.7 branch. But the interface changed so little there is a 99% chance that just bumping the version should be enough

**Comment by CryZe** [comment]
Yeah patching 0.7 is probably the cleanest way forward. It takes too long for 0.8 to propagate through the indirect dependencies.

**Comment by Ten0** [comment]
> I encourage everyone to not judge whether or not it was a good call but rather discuss how best to help this crate move forward.

It is possible to un-yank versions.

**Comment by tkaitchuck** [comment]
https://github.com/tkaitchuck/aHash/pull/175

**Comment by keehun** [comment]
I agree with @CryZe. Given how deeply buried `ahash` is in the dependency tree, it would be quite a while before they’re all resolved. If 0.7 could be bumped, that would probably end in the quickest resolution.

A somewhat less quick method but one that could also work well is to backport the fix that caused the yanking in the first place to 0.7.x and release a “hotfix”.

**Comment by tkaitchuck** [comment]
0.7.7 is now published

**Comment by partisan-bobryk** [comment]
@tkaitchuck much thanks! 🌮 🌮 🌮

**Comment by tkaitchuck** [comment]
0.4.8 is also published with a patch.

**Comment by dfeyer** [comment]
@tkaitchuck Thank you so much, what a blast and a fast move. Thanks

**Comment by keehun** [comment]
Thank you very much, @tkaitchuck!
