### ISSUE TITLE
Consider removing `zerocopy` dependency

### ISSUE THREAD

**Issue by a1phyr** [tkaitchuck/aHash#180]
Hi!

#162 added `zerocopy` dependency, which in turn brings `zerocopy_derive`, which brings all the proc-macro dependency. This pushes ahash very far in the compilation chain, which is damageable for such a fundamental crate.

Are you willing to revert #162, or at least to consider a cheaper alternative ?

**Comment by tkaitchuck** [comment]
Can you quantify this? From my POV,
If I just run `cargo build` for ahash it's only building 7 things and takes about 1 sec.

**Comment by SchrodingerZhu** [comment]
@a1phyr zerocopy_derive is gated by a flag and it is not effective in ahash.

**Comment by a1phyr** [comment]
I found out that it appeared in my Cargo.lock due to the proc-macro version trick (depending on the proc-macro with a `cfg(any())` target).

If no other dependency activates the feature this is fine I guess
