### ISSUE TITLE
Add Changelog to aid upgrade reviews

### ISSUE THREAD

**Issue by bheylin** [tkaitchuck/aHash#184]
Hi! Can you please add a changelog so that upgrade reviews of this lib
are simpler to perform.

Something like: https://keepachangelog.com/en/1.0.0/

Or tag release commits so one can compare two releases simply.

Thanks!

**Comment by tkaitchuck** [comment]
This: https://github.com/tkaitchuck/aHash/releases  ?

**Comment by bheylin** [comment]
Not sure how I missed that!
