### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by daxpedda** [tkaitchuck/aHash#188]
Rust Std currently depends on `ahash` through `stdarch`. But since `stdarch` is trying to change the name of some nightly features names, which the current version of `ahash` (v0.8.6) relies on, it is currently blocked (see https://github.com/rust-lang/rust/pull/117372) on a new release of `ahash` with https://github.com/tkaitchuck/aHash/pull/183.

A new release to unblock further work in Rust Std would be much appreciated!
Thank you.

**Comment by tkaitchuck** [comment]
0.8.7 is released.

**Comment by mina86** [comment]
Is there a chance to also get #183 backported to 0.7 branch and released in 0.7.8?
