### ISSUE TITLE
Make no_panic optional

### ISSUE THREAD

**Issue by cbeck88** [tkaitchuck/aHash#19]
My build started failing with

```
 = note: /root/mobilenode/target/debug/deps/libahash-72211b027529aaa9.rlib(ahash-72211b027529aaa9.ahash.4a8lpfqe-cgu.8.rcgu.o): In function `<ahash::hash_test_final::__NoPanic as core::ops::drop::Drop>::drop':
          /root/mobilenode/cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.2.9/src/lib.rs:195: undefined reference to `
          
          ERROR[no-panic]: detected panic in function `hash_test_final`
          '
          collect2: error: ld returned 1 exit status
```

I'm not sure why this started happening, I think it's because in this commit I'm using `hashbrown` + ahash in more targets?

It only fails during `cargo test` not during `cargo build`

In documentation of `no_panic` crate, it is suggested:

> If you find that code requires optimization to pass #[no_panic], either make no-panic an optional dependency that you only enable in release builds, or add a section like the following to Cargo.toml to enable very basic optimization in debug builds.

Would you consider making `no_panic` an optional dependency that's off by default? It's a pretty nice check but I think most users probably don't need to validate 3rd party library code this way as part of their builds, and would appreciate faster builds. I'm happy to make a patch like this.

**Comment by tkaitchuck** [comment]
Merged

**Comment by cbeck88** [comment]
thank you!
