### ISSUE TITLE
Deterministic hash value

### ISSUE THREAD

**Issue by cBournhonesque** [tkaitchuck/aHash#199]
Hi, 
Am I expected to get deterministic hash values across platforms if I use fixed seeds for the RandomState?

I am building the hasher with `RandomState::with_seeds(1, 2, 3, 4).build_hasher();`
but I noticed that I get different hash values when I run my code on different platforms.

**Comment by schungx** [comment]
It is deterministic across runs on the same platform.  I don't think it guarantees the exact same hash on multiple platforms and CPU architectures.

**Comment by tkaitchuck** [comment]
Yes. @schungx is correct. As it says in the Readme: 
> Because it does not have a fixed standard, different computers or computers on different versions of the code will observe different hash values. As such, aHash is not recommended for use other than in-memory maps.
