### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by vmosone** [tkaitchuck/aHash#22]
**Cargo.toml**
[package]
name = "test_dashmap"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[dependencies]
dashmap = "1.0"

**main.rs**
extern crate dashmap;

use dashmap::DashMap;

fn main() {
	let map: DashMap<usize, usize> = DashMap::default();
}

**cargo build**
Compiling ahash v0.2.12
error: cannot find macro `proc_macro_call!` in this scope
  --> C:\Users\vmos\.cargo\registry\src\github.com-1ecc6299db9ec823\ahash-0.2.12\src/lib.rs:49:45
   |
49 | static SEED: AtomicUsize = AtomicUsize::new(const_random!(u64));
   |                                             ^^^^^^^^^^^^^^^^^^
   |
   = help: have you added the `#[macro_use]` on the module/import?
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: cannot find macro `proc_macro_call!` in this scope
  --> C:\Users\vmos\.cargo\registry\src\github.com-1ecc6299db9ec823\ahash-0.2.12\src/lib.rs:92:32
   |
92 |         AHasher::new_with_keys(const_random!(u64), const_random!(u64))
   |                                ^^^^^^^^^^^^^^^^^^
   |
   = help: have you added the `#[macro_use]` on the module/import?
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: cannot find macro `proc_macro_call!` in this scope
  --> C:\Users\vmos\.cargo\registry\src\github.com-1ecc6299db9ec823\ahash-0.2.12\src/lib.rs:92:52
   |
92 |         AHasher::new_with_keys(const_random!(u64), const_random!(u64))
   |                                                    ^^^^^^^^^^^^^^^^^^
   |
   = help: have you added the `#[macro_use]` on the module/import?
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 3 previous errors

error: Could not compile `ahash`.

**Comment by vmosone** [comment]
[https://github.com/tkaitchuck/aHash/issues/12](url)

**Comment by tkaitchuck** [comment]
This looks a lot like: https://github.com/tkaitchuck/aHash/issues/17

I'll try to reproduce this. I am wondering if this could somehow be Windows speffic. Not sure how would be possible...

**Comment by vmosone** [comment]
First of all, thanks for your ahash.

I think I can ignore the windows platform for the time being.

look forward to your good ideas.

**Comment by tkaitchuck** [comment]
Well, if it is windows speffic, then that is a problem deeper in the tool chain that needs to be reported. So I'll try to reproduce it and we can go from there.

**Comment by tkaitchuck** [comment]
@vmosone Is this still an issue for you?
