### ISSUE TITLE
git source unaligned with crates.io release

### ISSUE THREAD

**Issue by jonassmedegaard** [tkaitchuck/aHash#224]
Git tag v0.8.11 contains code with a `Cargo.toml` file declaring version as 0.8.10.
Code is tagged on the same date as crates.io began offering version 0.8.11 which seems to be missing from git source.

I guess it was a simple mistake of pushing untracked code to crates.io...

**Comment by tkaitchuck** [comment]
It was pushed from the 0.8 release branch.

**Comment by tkaitchuck** [comment]
You can see the exact commit the release is based on in the release section: https://github.com/tkaitchuck/aHash/releases

**Comment by jonassmedegaard** [comment]
I see the branch now, yes. For some reason my local clone, updated with `git fetch <the_git_repo> --tags`, failed to fetch the tag `v0.8.11` till now, which lead me to miss that branch.

Sorry for the noise.

**Comment by jonassmedegaard** [comment]
Ahh, no, the tag was there all along, and my point is that the _contents_ is not matching: See https://github.com/tkaitchuck/aHash/compare/v0.8.10...v0.8.11 how the version number in `Cargo.toml` is changed not to 0.8.11 but to 0.8.10.

**Comment by jonassmedegaard** [comment]
Seems you accidentally tagged HEAD of master branch, instead of  HEAD of the release-0.8 branch.
