### ISSUE TITLE
rust v1.78 std simd feature removed

### ISSUE THREAD

**Issue by jianshu93** [tkaitchuck/aHash#227]
Hello Team,

When I was compiling hashbrown under nightly rust 1.78 and 1.79, which relies on ahash, 0.8.6, I have the following error: 

error[E0635]: unknown feature `stdsimd`
  --> /storage/home/hcoda1/4/jzhao399/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.6/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]

Now it is called "portable-simd"

Thanks,

Jianshu

**Comment by tkaitchuck** [comment]
Yes. This was fixed in 0.8.7. If you update to the latest in the 0.8 branch it should be fully compatible
