### ISSUE TITLE
Mismatch between published version on crates.io and tagged version in git repo for v0.8.11

### ISSUE THREAD

**Issue by VorpalBlade** [tkaitchuck/aHash#232]
Using cargo-goggles I discovered that ahash has differences between the version on crates.io and the version in the repo at the tag v0.8.11:

* The tests are missing in lib.rs on crates.io
* The tests are different in operations.rs on crates.io
* In specialize.rs there are larger differences around `CallHasher`

In the Cargo.toml the version is wrong in the git version (v0.8.10).

The changes don't seem malicious (and I would assume this is an honest mistake with placing the tag at the wrong commit), but they are somewhat concerning given the recent xz backdoor. I would like an explanation of what is going on here.

**Comment by tkaitchuck** [comment]
The 0.8 releases are released from the 0.8-release branch. The master branch has some unreleased changes, that will be included in future releases. Those are the only differences I am aware of.

**Comment by VorpalBlade** [comment]
Hm, I checked out the *tag* v0.8.11 and compared that to the version from crates.io. They didn't quite match, and it seems like the tag simply points to an older commit (from before 0.8.10 was changed to 0.8.11).

**Comment by tkaitchuck** [comment]
Ok, it looks like I just tagged the last PR in the release as opposed to the PR with the version bump. That's is an issue in that if the tag is checked out it will list the wrong version in the toml. (I don't know if / when that is relevant) But it looks like the only way to fix that is a force push, which I am reluctant to do as it rewrites history.

**Comment by VorpalBlade** [comment]
Would it not be possible to just repoint the tag to a different version? Tags can be moved. You don't need to force push actual *commits* (which I agree would be bad).

https://stackoverflow.com/questions/8044583/how-can-i-move-a-tag-on-a-git-branch-to-a-different-commit comes up when searching for this (I admit I didn't know, I normally use SmartGit as a GUI for git when doing "scary" operations, as I find it is much more obvious what exactly I'm doing.)

**Comment by tkaitchuck** [comment]
@VorpalBlade Ah, thank you. I didn't realize the `-d` flag existed. I only saw the top response with the `-f`. 
The tag is now updated. 
Shall I close this?

**Comment by VorpalBlade** [comment]
@tkaitchuck just turned off my computer for the evening (writing this on my phone), so I won't be able to provide feedback on this until after work tomorrow.

**Comment by VorpalBlade** [comment]
This seems to be fixed now. Thank you very much.
