### ISSUE TITLE
Backport stdsimd removal fix to 0.7.x

### ISSUE THREAD

**Issue by Ciantic** [tkaitchuck/aHash#241]
This was suggested here: https://github.com/tkaitchuck/aHash/issues/200#issuecomment-1929526236

I think it would be a good idea, it could fix a lot of things upstream. 

Currently, only way to fix broken packages is to use this in Cargo.toml

```
[patch.crates-io]
ahash = { git = "https://github.com/tkaitchuck/aHash" }
```

It will force the ahash even if something in your upstream depends on ahash (e.g. hashbrown, looking at you)

Thanks for considering.

**Comment by tkaitchuck** [comment]
This was released in 0.7.8: https://github.com/tkaitchuck/aHash/issues/200#issuecomment-1937361258
