### ISSUE TITLE
Cannot compile ahash if "compile-time-rng" feature is disabled and the environment is not "no_std"

### ISSUE THREAD

**Issue by loiclec** [tkaitchuck/aHash#26]
Hello 👋 

I cannot compile the crate if I disable the "compile-time-rng" feature. The issues seems to be because the `const_random` crate is imported anyway, (unless the environment is not `no_std`) here: https://github.com/tkaitchuck/aHash/blob/a7c0b5a938404a6dc2e58a51fdbfe1b0a6b183bd/src/lib.rs#L16-L17 which is strange because a few lines later, another use of `const_random` is guarded under a different condition: https://github.com/tkaitchuck/aHash/blob/a7c0b5a938404a6dc2e58a51fdbfe1b0a6b183bd/src/lib.rs#L33-L34

And thank you for the crate, it really helped me speed up my program!

(edit: oops, sorry, I just noticed that there is already a pull request to fix this! https://github.com/tkaitchuck/aHash/pull/25)

**Comment by tkaitchuck** [comment]
#25 is merged in version 0.2.18
