### ISSUE TITLE
What is hash_test[_aes] for?

### ISSUE THREAD

**Issue by CryZe** [tkaitchuck/aHash#28]
Those seem like dead code, but they show up as public exports in my WebAssembly. If they are necessary for some automated testing, maybe they could be moved to some testing feature flag?
```
 (export "hash_test" (func $hash_test))
```

**Comment by tkaitchuck** [comment]
Those are there as inspection points so that I can easily locate and read the generated assembly. 
It's weird they are they showing up as public? They aren't `pub`. They don't show in docs...

I could put them behind a feature flag, but it's probably easier to comment them out.

**Comment by tkaitchuck** [comment]
Commented out in 0.3.1
