### ISSUE TITLE
RandomState::build_hasher documentation is misleading

### ISSUE THREAD

**Issue by CAD97** [tkaitchuck/aHash#30]
> `fn build_hasher(&self) -> AHasher`
> 
> Constructs a new `AHasher` with keys based on compile time generated constants** and the location of the this object in memory.

When reading this, it scared me initially, as with the docs as written, moving the `BuildHasher` would change the key used to generate the real `Hasher`.

The correct description of the behavior is that the keys are "based on compile compile time generated constants and the location this object was constructed at in memory."

**Comment by tkaitchuck** [comment]
Fixed: https://github.com/tkaitchuck/aHash/commit/0d3ccb64ff7aa7f74552b9a0806868a74708f40d
