### ISSUE TITLE
Allow setting RandomState construction seed using runtime randomness

### ISSUE THREAD

**Issue by dtolnay** [tkaitchuck/aHash#31]
https://github.com/tkaitchuck/aHash/blob/5f365dd27d9f5527e89c1b1f01f302f5720b8375/src/random_state.rs#L13-L17

Nondeterministic builds are problematic in some environments, for example a Buck-based codebase that uses distributed caching of build artifacts -- distributed build caches incorporate an assumption that build outputs are a deterministic function of the inputs. When this is not the case, it can cause a mismatch between what we think should be in cache vs what can actually be retrieved from the cache by content hash.

But when using ahash with compile-time-rng disabled, we'd still like to avoid having a predictable sequence of states produced by RandomState::new().

Would you consider exposing a setter for random_state::SEED to allow populating it with runtime randomness at startup?

```rust
ahash::RandomState::set_seed(rand());
```

**Comment by tkaitchuck** [comment]
Done: https://github.com/tkaitchuck/aHash/commit/18d005c9f19639ff546b5e99fe7978fe87539abe
