### ISSUE TITLE
Support for running under miri

### ISSUE THREAD

**Issue by jonhoo** [tkaitchuck/aHash#32]
This may be a tricky one, I'm not sure.

When running any code that uses `ahash` through [miri](https://github.com/rust-lang/miri/) to check for unsafe code, miri runs into issues with ahashes use of per-arch accelerated instructions like `std::arch::x86_64::_mm_aesdec_si128`. Specifically, the user ends up with an error like
```
error: unsupported operation: can't call foreign function: llvm.x86.aesni.aesdec
    --> /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/../stdarch/crates/core_arch/src/x86/aes.rs:39:5
     |
39   |     aesdec(a, round_key)
     |     ^^^^^^^^^^^^^^^^^^^^ can't call foreign function: llvm.x86.aesni.aesdec
     |
     = help: this is likely not a bug in the program; it indicates that the program performed an operation that the interpreter does not support
     = note: inside `std::arch::x86_64::_mm_aesdec_si128` at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/../stdarch/crates/core_arch/src/x86/aes.rs:39:5
     = note: inside `ahash::aes_hash::aeshashx2` at /home/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.3.2/src/aes_hash.rs:189:21
     = note: inside `ahash::aes_hash::AHasher::hash_in` at /home/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.3.2/src/aes_hash.rs:58:23
     = note: inside `<ahash::aes_hash::AHasher as std::hash::Hasher>::write_u128` at /home/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.3.2/src/aes_hash.rs:87:9
     = note: inside `<ahash::aes_hash::AHasher as std::hash::Hasher>::write_u64` at /home/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.3.2/src/aes_hash.rs:97:9
     = note: inside `<ahash::aes_hash::AHasher as std::hash::Hasher>::write_usize` at /home/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.3.2/src/aes_hash.rs:92:9
     = note: inside `std::hash::impls::<impl std::hash::Hash for usize>::hash::<ahash::aes_hash::AHasher>` at /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/hash/mod.rs:569:21
```
While we could leave it to miri to mock out all of these functions, it might be easier (I don't know) for ahash to simply use the fallback hash implementation under `cfg(miri)`. I _think_ this should just be a matter of changing
https://github.com/tkaitchuck/aHash/blob/e7a92205f6c80060dec19733e6ca2ed2c74b643e/src/lib.rs#L20
and other `cfg`s like it to include `not(miri)` in the `all` list.

/cc @RalfJung

**Comment by tkaitchuck** [comment]
I can do this. But I am not sure that would do what you want. Because it may mean that the check of the unsafe behavior will check different code then will actually be used when AES is available.

**Comment by RalfJung** [comment]
Well, it's still better than no testing of anything that depends on this.

**Comment by tkaitchuck** [comment]
Maybe there is a different issue here, if miri does not support aes, why is the `target_feature = aes` getting set to `true`?

**Comment by RalfJung** [comment]
Unfortunately there is no good way for Miri to influence `target_features`. After all, the *target* supports aes, but the "codegen backend" does not.

Also see https://github.com/rust-lang/miri/issues/932.

**Comment by tkaitchuck** [comment]
Done: https://github.com/tkaitchuck/aHash/commit/ca2f39087f79eb92760ed4d6a3619df1b073eb5b

**Comment by jonhoo** [comment]
@tkaitchuck Would you mind pinging here when a new release is out with that change?

**Comment by tkaitchuck** [comment]
@jonhoo version 0.3.4 includes this change
