### ISSUE TITLE
Is hashing a tuple (u32, u32, u32) the same as u128?

### ISSUE THREAD

**Issue by jestarray** [tkaitchuck/aHash#35]
Hello! my game hashes tile coordinates. `HashMap<(u32,u32,u32), Vec<Entity>)` and I was wondering if it's the same as hashing a u128.

edit: woops, just realized this is 96 bits... still unsure which bucket tuples fall into in this case.

**Comment by Amanieu** [comment]
No, the `Hash` trait only guarantees consistent results if you pass in the exact same values with the exact same types. The `Hash` impl for `(u32, u32, u32)` passes 3 `u32` values while `u128` is hashed on its own.

**Comment by jestarray** [comment]
Ah, so this is treated as a 15 byte string?

**Comment by Amanieu** [comment]
No, a 15 byte string would be hashed as 15 `u8` values.

**Comment by tkaitchuck** [comment]
The form of the data matters to the hasher. So 4 u32s is not the same as 1 u128. However it is possible to cheaply convert between items of the same size. There is a slight performance gain by dealing with a single larger item rather then multiple individual ones. (aHash will be able to automatically take advantage of this once specialization lands in stable Rust).

Regardless, for consistency this means that for data you want to hash the same way it always needs to be passed in the same "shape".
