### ISSUE TITLE
Fails to build without std feature enabled

### ISSUE THREAD

**Issue by adamreichold** [tkaitchuck/aHash#36]
Versions 0.3.6 and 0.3.7 fail to build without the `std` feature enabled, e.g. if only a direct dependency on `hashbrown` is used which depends on `ahash` without default features.

The error message is
```
error[E0433]: failed to resolve: use of undeclared type or module `std`
 --> /home/adam/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.3.7/src/aes_hash.rs:4:5
  |
4 | use std::hint::unreachable_unchecked;
  |     ^^^ use of undeclared type or module `std`

error: aborting due to previous error
```

**Comment by vadixidav** [comment]
Getting the same issue.

Workaround:

```toml
ahash = "=0.3.6"
```

**Comment by tkaitchuck** [comment]
Fixed https://github.com/tkaitchuck/aHash/commit/317347818a5120f3ff2a7f14d66aa9b88e10df59
