### ISSUE TITLE
use typedef for AHashMap/AHashSet

### ISSUE THREAD

**Issue by pmarks** [tkaitchuck/aHash#42]
I was trying to switch some code over to AHashMap/AHashSet, but serde::{Serialize,Deserialize} aren't implemented for them, because of the newtype wrapper.

Wondering if a better strategy for exposing these would be typedefs?  This is what [fxhash does](https://github.com/cbreeden/fxhash/blob/master/lib.rs#L43). That has the advantage of interoperating more cleanly with the rest of the ecosystem, because any external trait implemented for the stdlib type are still valid for the typedefs.   I'm not aware of any drawbacks in this case.  Thoughts?

**Comment by tkaitchuck** [comment]
See the comment here: https://github.com/tkaitchuck/aHash/pull/23

Not having `new` or `with_capacity` would be a major disadvantage. Maybe there is some way to get the best of both. 

The wrapper already implements deref, so depending on the situation I would think that attempting to pass it where a HashMap was expected would generally work. Would adding implementations of `From` and `Into` work for your situation?

**Comment by tkaitchuck** [comment]
From and into added: https://github.com/tkaitchuck/aHash/commit/e8b0a5d61781595ec87c40d0748e32cfaa9ceeb3
