### ISSUE TITLE
Allow enabling of AES-NI support through a feature flag

### ISSUE THREAD

**Issue by YorickPeterse** [tkaitchuck/aHash#43]
This crate currently enables AES support if AES-NI support is detected (by `target_feature=+aes` being set somehow). To the best of my knowledge, the only way of setting this option is by setting RUSTFLAGS or by passing `-C ...` to `rustc` somehow. Sadly Cargo does not provide a sane way (that I know of) for passing such settings conditionally. Instead, you either have to pass it manually or pass it always.

But there is a way around this: aHash could include a `build.rs` that looks like this:

```rust
fn main() {
    if cfg!(feature = "aes") {
        println!("cargo:rustc-cfg=target_feature=\"aes\"");
    }
}
```

This allows setting of target_feature settings for this crate, which can then be driven by a feature flag set through Cargo. aHash could then enable AES support if it either detects AES-NI support on its own, or when forced by setting this feature flag. This in turn allows depending crates to reuse this functionality. All this makes it easier to (conditionally) build depending crates (and aHash) with or without AES-NI support. 

For example, if project X depends on aHash, this setup allows users of X to enable/disable AES-NI support easily; instead of having to set RUSTFLAGS. It also allows X to enable it by default, something you can't really do with RUSTFLAGS easily that I know of (at least not without requiring users to go through a `Makefile` or edit `Cargo.toml` by hand).

I'd be happy to provide a patch adding support for this. But before I do so: does this sound reasonable, or are there perhaps better ways of doing this that I am not aware of?

**Comment by YorickPeterse** [comment]
Context:

In [this issue](https://gitlab.com/inko-lang/inko/-/issues/211) I looked into enabling AES-NI support for a project of mine. I would like to enable it for all x86-64 CPUs by default, without locking the project down to specific architectures (e.g. Skylake). Using a feature flag seems most reasonable: it would be enabled by default, and if desired users can still disable it (e.g. when compiling on an x86-64 CPU that for some reason doesn't support the feature). 

Assuming aHash would support the proposed setup, all I'd have to do in this case is add something like this to my `Cargo.toml`:

```toml
[features]
default = ["aes"}
aes = ["ahash/aes"]
```

Users can then build the project like so:

    cargo build --no-default-features # No AES support
    cargo build # AES support

**Comment by Amanieu** [comment]
That just enables the cfg flag but AFAIK doesn't actually make rustc use the AES instructions. In particular this will causes issues since LLVM not inline the AES intrinsics from `core::arch`, which will end up hurting performance overall.

The only way to make this work is with `RUSTFLAGS` or via `.cargo/config`.

**Comment by YorickPeterse** [comment]
@Amanieu That's a bummer. Thanks for the info, I'll close this issue then :smiley:

**Comment by YorickPeterse** [comment]
@Amanieu Just to double check: wouldn't the `build.rs` option emitted have the same effect as `RUSTFLAGS` setting it?

**Comment by YorickPeterse** [comment]
It seems the `build.rs` approach indeed does not work as I expected. I used this `build.rs`:

```rust
fn main() {
    println!("cargo:rustc-cfg=target_feature=\"aes\"");
}
```

I then used a `main.rs` that looks like this:

```rust
use std::process::exit;

fn aesenc(value: u128, xor: u128) -> u128 {
    use core::arch::x86_64::*;
    use core::mem::transmute;

    unsafe {
        let value = transmute(value);
        transmute(_mm_aesenc_si128(value, transmute(xor)))
    }
}

fn main() {
    let x = aesenc(42, 48);

    // This is just to make sure the `x` is not optimised away.
    if x > 0 {
        exit(0);
    }
}
```

I then used [cargo-asm](https://github.com/gnzlbg/cargo-asm) to get the assembly of the `main` function. I ran it like so ("playground" is the project name):

```
cargo asm --build-type release playground::main
```

This outputs the following:

```
playground::main:
 sub     rsp, 56
 mov     eax, 42
 movq    xmm0, rax
 movdqa  xmmword, ptr, [rsp, +, 16], xmm0
 mov     eax, 48
 movq    xmm0, rax
 movdqa  xmmword, ptr, [rsp, +, 32], xmm0
 mov     rdi, rsp
 lea     rsi, [rsp, +, 16]
 lea     rdx, [rsp, +, 32]
 call    core::core_arch::x86::aes::_mm_aesenc_si128
 mov     rax, qword, ptr, [rsp]
 or      rax, qword, ptr, [rsp, +, 8]
 jne     .LBB5_2
 add     rsp, 56
 ret
.LBB5_2:
 xor     edi, edi
 call    qword, ptr, [rip, +, _ZN3std7process4exit17h88a2719248972658E@GOTPCREL]
 ud2
```

Note the `call` to the AES function. If I set the target feature via RUSTFLAGS, it gets inlined:

```
playground $ env RUSTFLAGS="-C target-feature=+aes" cargo asm --build-type release playground::main 
playground::main:
 push    rax
 mov     eax, 48
 movq    xmm0, rax
 mov     eax, 42
 movq    xmm1, rax
 aesenc  xmm1, xmm0
 movq    rax, xmm1
 pshufd  xmm0, xmm1, 78
 movq    rcx, xmm0
 or      rcx, rax
 jne     .LBB4_2
 pop     rax
 ret
.LBB4_2:
 xor     edi, edi
 call    qword, ptr, [rip, +, _ZN3std7process4exit17h88a2719248972658E@GOTPCREL]
 ud2
```

So it seems you're right: RUSTFLAGS or `.cargo/config` is the only way to make this work :cry:
