### ISSUE TITLE
Hash results between release and debug build differs

### ISSUE THREAD

**Issue by brmmm3** [tkaitchuck/aHash#47]
I'm facing a strange issue. When I calculate the hash value of a binary blob with size 920603 in release and debug build I get different hash results.
I'm calculating the hash value with the following code:
```
let mut hasher = AHasher::default();
hasher.write(&data);
cksum = hasher.finish()
```
I'm using rustc 1.48.0-nightly (0e2c1281e 2020-09-07) on Windows. I couldn't test it yet with stable because my project depends on unstable features.

**Comment by tkaitchuck** [comment]
AHasher::default() is implemented via: `AHasher::new_with_keys(const_random!(u128), const_random!(u128))`
So every time you compile it you should get different keys, and hence different output values.

If you want different binaries to arrive at the same hash output, you have to specify the keys.

Be advised that aHash does not have a fixed standard for its algorithm, so if you compile two different versions of aHash or with different compiler/feature flags you will end up with different hash values even if you specify the keys.
