### ISSUE TITLE
`const_random` compile error: mismatched types

### ISSUE THREAD

**Issue by jstrong-tios** [tkaitchuck/aHash#49]
ahash v0.2.18, a subdependency fairly far deep down in my `cargo tree`, is failing to compile (via `cargo test`) with this message:

```console
error[E0308]: mismatched types
  --> /home/jstrong/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.2.18/src/lib.rs:55:45
   |
55 | static SEED: AtomicUsize = AtomicUsize::new(const_random!(u64));
   |                                             ^^^^^^^^^^^^^^^^^^ expected `usize`, found `u64`
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `ahash`
```
I did not see any other reports of this particular error, but may have missed it.

Seems like the fix would be simple, to cast the return value of `const_random!(u64)` to usize? I'm confused how this previously compiled, though, seems like I am missing some part of the picture. 

using `rustc 1.49.0-nightly (98edd1fbf 2020-10-06)`

**Comment by tkaitchuck** [comment]
It appears to be an incompatibility with this change: https://github.com/tkaitchuck/constrandom/pull/11 to const_random.

**Comment by tkaitchuck** [comment]
aHash versions newer than 0.3.5 should not be affected. I can yank 0.2 builds to prevent more people from hitting this.

**Comment by tkaitchuck** [comment]
Older versions yanked. @jstrong-tios can you confirm that newer versions work for you?

**Comment by jstrong-tios** [comment]
I can confirm that newer versions of ahash compile fine for me.

the result of yanking the older versions is this error:

```console
$ cargo update
error: failed to select a version for the requirement `ahash = "^0.2.11"`
candidate versions found which didn't match: 0.4.5, 0.4.4, 0.4.3, ...
location searched: crates.io index
required by package `hashbrown v0.6.0`
    ... which is depended on by `lru v0.4.0`
    ... which is depended on by `rv v0.10.0`
    ... which is depended on by `mycrate v0.1.0 (/path/to/mycrate)`
error: Recipe `cargo` failed on line 5 with exit code 101
```

that will likely prompt quick action on the downstream crates depending on the older version of hashbrown (0.6) which is the biggest source of this. however, it may also prompt some confusion.

(just to clarify if you are coming across this for a solution - ahash needs to be upgraded to >= 0.3.5)

**Comment by gperinazzo** [comment]
This also broke the 0.8.x releases of hashbrown that are still widely used.

**Comment by tkaitchuck** [comment]
It looks like hashbrown 0.7 and newer should not be affected. Looking through HashBrown's dependent packages on crates.io https://crates.io/crates/hashbrown/reverse_dependencies
I see a number of things depending on earlier versions. 

I will put together a new 0.2 release so that old versions of hashbrown can continue to work.

**Comment by tkaitchuck** [comment]
Done: https://github.com/tkaitchuck/aHash/tree/release-0.2
0.2.19 should resolve the compile error in the 0.2 branch.

**Comment by jonathanstrong** [comment]
thanks for responding quickly to this! I think adding the 0.2.19 version was a good solution.
