### ISSUE TITLE
Adding a feature for serde

### ISSUE THREAD

**Issue by maxtremblay** [tkaitchuck/aHash#60]
Hello, I used this hasher in a project and I noticed that `'AHashMap` and `AHashSet` are not implementing `serde::Serialize` nor `serde::Deserialize` traits. I copy/paste chunk of codes from serde directly to implement it for a local copy. 

Would you be interested in me cleaning that up and adding that as a feature to this crate?

**Comment by tkaitchuck** [comment]
The following example works for me:
```rust
#[cfg(test)]
mod tests {
    use ahash::{AHashMap, AHasher, RandomState};
    use std::collections::HashMap;

    #[test]
    fn test_map_serde() {
        let mut map = AHashMap::new();
        map.insert(1, 2);
        let serialized = serde_cbor::to_vec(&*map).expect("serialization failed");
        let deserialized : HashMap<i32, i32, RandomState> = serde_cbor::from_slice(&serialized).expect("Deserialization failed");
        let map_copy: AHashMap<i32, i32> = deserialized.into();
        assert_eq!(map, map_copy);
    }
}
```

What is the issue you are running into?

**Comment by tkaitchuck** [comment]
Are you dealing with a larger structure which contains a map?

**Comment by maxtremblay** [comment]
Yes, I have a struct containing two maps and I wasn't able to derive Serialize for this struct.

**Comment by maxtremblay** [comment]
I guess one solution is to add something like this 

```

**Comment by tkaitchuck** [comment]
Something like that looks reasonable. It would have to go behind a feature flag. (Which is annoying because the number of those is rapidly growing)

**Comment by maxtremblay** [comment]
I made PR #61.

**Comment by tkaitchuck** [comment]
Merged
