### ISSUE TITLE
Document reasons for yanking versions from https://crates.io

### ISSUE THREAD

**Issue by olson-sean-k** [tkaitchuck/aHash#63]
Numerous versions of `ahash` have been yanked from https://crates.io, but it is difficult to determine why any particular version was taken down. When dependent builds fail due to a yank, it could be useful and informative to see why the yanked version of `ahash` was removed from the registry, especially if build artifacts that include such a version of `ahash` are still out in the wild.

Considering the number of yanks (46 in total at the time of this writing), perhaps a "yank log" could be introduced so users can see why a version they've depended upon must be avoided. Thoughts?

**Comment by tkaitchuck** [comment]
Done:
https://github.com/tkaitchuck/aHash/wiki/Yanked-versions

**Comment by olson-sean-k** [comment]
Awesome! Thanks for putting this together!
