### ISSUE TITLE
Switch from lazy_static to once_cell

### ISSUE THREAD

**Issue by jplatte** [tkaitchuck/aHash#65]
[once_cell](https://crates.io/crates/once_cell)::sync::Lazy fulfills the same task as `lazy_static` but is less magic in that it doesn't require a macro. A lot of crates have switched already and std has adopted large parts of `once_cell`s API surface as a Nightly feature ([tracking issue](https://github.com/rust-lang/rust/issues/74465)). Would you be open to a PR that switches aHash over too?

**Comment by tkaitchuck** [comment]
I prefer once_cell. I actually started with it. However it pulls in a huge number of transitive dependencies (or at least it did when I last checked), and I would like to keep aHash as light as possible given how low level it is.

**Comment by jplatte** [comment]
Just checked, `once_cell` has a single optional dependency (`parking_lot`). Same for version 1.0.1 (1.0.0 is yanked). Maybe a pre-1.0 version had more deps, but it's certainly not the case now 🙂

**Comment by tkaitchuck** [comment]
I think the trouble is that I would need parking_lot. Per the doc:

> To implement a sync flavor of OnceCell, this crates uses either a custom re-implementation of std::sync::Once or parking_lot::Mutex. This is controlled by the parking_lot feature, which is enabled by default. Performance is the same for both cases, but the parking_lot based OnceCell<T> is smaller by up to 16 bytes.

Which is sort of a shame, because the whole reason for the need for the lock is to block to make sure the initialization code doesn't get run multiple times. However I don't actually care about that. If there were an "ApproximatelyOnceCell" with zero deps that would be ideal.

**Comment by jplatte** [comment]
I don't exactly understand. Is it that you wouldn't want to use `once_cell` with a 16 byte overhead?

**Comment by tkaitchuck** [comment]
I don't care about the 16 bytes. I care about pulling in a dependency on parking_lot. If I can avoid having all those deps and get a working solution I'd be happy. I created https://github.com/matklad/once_cell/issues/133 to track the issue. Either of  https://github.com/matklad/once_cell/issues/61 or https://github.com/matklad/once_cell/issues/53 would also be acceptable.

**Comment by jplatte** [comment]
Oh, so the issue is `no_std` support. That wasn't clear before. Thanks for following up with `once_cell`, I'm curious to see where that goes; it would be relevant for tracing too (https://github.com/tokio-rs/tracing/issues/1165).

**Comment by tkaitchuck** [comment]
Ok. https://github.com/tkaitchuck/aHash/commit/c828cc6c786e2d80ee867e7dd54443e9b3d017f8
Will be included in the next release.
