### ISSUE TITLE
Zero keys always result in a zero hash

### ISSUE THREAD

**Issue by bjorn3** [tkaitchuck/aHash#70]
```rust
use std::hash::{Hash, Hasher};
use ahash::AHasher;

fn main() {
    let mut hasher1 = AHasher::new_with_keys(0, 0);
    let mut hasher2 = AHasher::new_with_keys(0, 0);
    "foo".hash(&mut hasher1);
    "bar".hash(&mut hasher2);
    assert_eq!(hasher1.finish(), 0);
    assert_eq!(hasher2.finish(), 0);
}
```

Noticed by @TheRawMeatball at the Bevy discord: https://discord.com/channels/691052431525675048/749335865876021248/801422400326729728

**Comment by tkaitchuck** [comment]
Yes. The prefered way to initialize from constants is using [`RandomState.generate_with`](https://docs.rs/ahash/0.6.3/ahash/struct.RandomState.html#method.generate_with) if you want different keys to be used or [`AHasher::default()`](https://docs.rs/ahash/0.6.3/ahash/struct.AHasher.html#impl-Default) when a fixed seed is desired.

The link is not working for me (it just directs to discord in general but not any channel) so I can't see context. Do these methods fit with your needs?

`new_with_keys` is really used for internal purposes to instantiate the state once appropriate keys have been generated. I don't want to add additional mixing at that point for performance reasons. It is only exposed for test purposes. Perhaps I should add the `#[doc(hidden)]` annotation to it.

**Comment by tkaitchuck** [comment]
Wait. I take all that back.

I already specialized the internal implementation to avoid this and added a path to do mixing on the public method, I just only did it for the fallback because it is the one with this problem. You might be running on nightly and hitting the recently added short string path. I'll fix that

**Comment by tkaitchuck** [comment]
@bjorn3 Does this fix the problem for you?
https://github.com/tkaitchuck/aHash/pull/71

**Comment by tkaitchuck** [comment]
Reopening to confirm resolution

**Comment by bjorn3** [comment]
I can confirm that the problem is fixed. Thanks!
