### ISSUE TITLE
Force consistent random seed at compile time

### ISSUE THREAD

**Issue by rob-p** [tkaitchuck/aHash#80]
Hi, 

  I'd like to consider using aHash in a project in our lab (https://github.com/COMBINE-lab/alevin-fry).  In particular, we have a few places in the code where we make use of a greedy heuristic to solve a hard problem, where the exact result one gets depends on the order in which keys are observed.  Using standard hashers, this is a bit of an inconvenience, since you can run the program multiple times on exactly the same (deterministic) input and get slightly different results. The results are all equally "correct", since the greedy algorithm breaks ties randomly, but it would be desirable to have exact reproducibility between runs here.

  I noticed that aHash supports using a const (compile-time) random number generator "when a random source is not present at runtime".  Is it possible to _force_ aHash to use a const random number, even if a runtime source is present?  Is there any way to enforce that, in the same binary, the randomness will be the same between runs?

Thanks!

**Comment by tkaitchuck** [comment]
Yes. This is supported you can use the [`with_seeds` method](https://docs.rs/ahash/0.7.2/ahash/struct.RandomState.html#method.with_seeds) to manually supply a specific seed to the hashing algorithm.

**Comment by rob-p** [comment]
This is great!  Thank you for the pointer; I'll try it out.
