### ISSUE TITLE
ahash 0.7.2 test suite fails on 32-bit architectures

### ISSUE THREAD

**Issue by decathorpe** [tkaitchuck/aHash#83]
I'm building ahash 0.7.2 packages for Fedora, and I see three test failures on 32-bit architectures (x86 and armv7hl):

```
failures:
---- hash_quality_test::fallback_tests::fallback_keys_change_output stdout ----
thread 'hash_quality_test::fallback_tests::fallback_keys_change_output' panicked at '80513b7ff03f720b vs 80513b7ff03f720b: 8', src/hash_quality_test.rs:6:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- hash_quality_test::fallback_tests::fallback_keys_affect_every_byte stdout ----
thread 'hash_quality_test::fallback_tests::fallback_keys_affect_every_byte' panicked at 'assertion failed: `(left == right)`
  left: `18446744073709551615`,
 right: `18446744072640004095`: Bits changed: ffffffffc03fffff on num: 13', src/hash_quality_test.rs:150:5
---- hash_quality_test::fallback_tests::fallback_single_key_bit_flip stdout ----
thread 'hash_quality_test::fallback_tests::fallback_single_key_bit_flip' panicked at 'cb6ae85967184a78 vs cb6ae85967184a78: 8', src/hash_quality_test.rs:6:5
failures:
    hash_quality_test::fallback_tests::fallback_keys_affect_every_byte
    hash_quality_test::fallback_tests::fallback_keys_change_output
    hash_quality_test::fallback_tests::fallback_single_key_bit_flip
```

Looks like at least two of those might be caused by integer overflow issues (which cause panic!s in release mode).

**Comment by tkaitchuck** [comment]
> Looks like at least two of those might be caused by integer overflow issues (which cause panic!s in release mode).

I think you meant debug mode. Either way aHash is using nopanic and handles all integer overflow explicitly.

 These all involve assertions about the keys. My guess the key mixing on 32 bit is causing some of the input key bits not affect all bits to affect key2 but not key1 so it doesn't end up in `pad` or `buffer` but only in `extra_keys`. 

If that's the case it is not a serious issue.
I'll look into it.

**Comment by decathorpe** [comment]
Your're right, I mixed up debug and release mode ...

Thanks for looking into it!

**Comment by tkaitchuck** [comment]
Fixes. It was what I described above. I've added github actions check to prevent regression.

**Comment by decathorpe** [comment]
Great, thank you!
