### ISSUE TITLE
AES on ARM?

### ISSUE THREAD

**Issue by Artoria2e5** [tkaitchuck/aHash#84]
I noticed that [`core_arch`](https://docs.rs/core_arch/0.1.5/core_arch/aarch64/index.html) currently has intrinsics for AArch64's AES extensions, namely `vaeseq_u8` and `vaeseq_u8`. They seem to fit pretty well into the `(u128, u128) -> u128` signatures in `operations.rs` as far as i can tell.

While we are at it... The shuffle being replaced by a byteswap smells a little bit fishy, especially given the comment that the shuffle mask is specially chosen. Maybe a manual or `core_simd` shuffle can be written there for targets that do have a shuffle instruction, so that the codegen will do its job? (That would be AArch64, wasm, and many more.)

**Comment by tkaitchuck** [comment]
Is there an arm instruction that can perform the shuffle or something close? On x86_64 this isn't relevant because the shuffle is available on essentially all cpus with the are instruction. But arm may have different requirements.

Do you have an arm64 host to benchmark on?

**Comment by Artoria2e5** [comment]
I don't quite have one, except for... maybe my Android phone (I suppose I can set up a chroot, but even then with all the other programs running performance is not going to be consistent). General-case shuffle on ARM is done by two vtbl instructions, since each instruction can only do half an SIMD register.

**Comment by tkaitchuck** [comment]
The instruction is actually even better than what's on x86: https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?page=124
It xors the key first. This should allow it to be even faster, but I'll have to design the code path differently. I don't really feel comfortable doing that blind. I am going to flag this as "help_wanted" and delay implementation until I can find a suitable test setup.

**Comment by sebpop** [comment]
I can help benchmark and test your code on AWS Graviton2 and on M1 Apple.

**Comment by tkaitchuck** [comment]
@sebpop Awesome. Thanks.
