### ISSUE TITLE
64-bit version of `RandomState`

### ISSUE THREAD

**Issue by reinerp** [tkaitchuck/aHash#87]
For randomized hash tables, we need to store `RandomState` in the metadata for each table. For most applications, 64 bits of entropy in the hash seed is plenty, and indeed most hashers use `u64` seeds. But in ahash, we are required to store 256 bits, which is fairly large; this overhead is particularly significant when the hash table is empty.

Can we have a 64-bit of `RandomState`, that only expands to 256 bits of internal state when the `AHasher` object is formed?

Alternatively, some guidance on how to roll this as a user of `aHash` would be great. For example, suppose I have `hash_seed: u64`. Would the following snippet generate a reasonable `AHasher` instance?

```
fn make_hasher(h: u64) -> AHasher {
  let h = h as u128;
  let h = h | (h << 64);
  AHasher::new_with_keys(h, h)
}
```

**Comment by tkaitchuck** [comment]
This https://docs.rs/ahash/0.7.4/ahash/struct.RandomState.html#method.with_seeds 
Can be safely called with the same value for all four arguments.

**Comment by tkaitchuck** [comment]
The code you have there would also work.

In both cases, if you look at the impl of the method it is xoring the provided input with the digits of PI to prevent re-using the same key element in multiple places from causing problems.

**Comment by tkaitchuck** [comment]
I have made this explicit in [the documentation](
https://github.com/tkaitchuck/aHash/commit/f468cb620c8998c9acecec1911de06bc61629c51#diff-a8577224d6d9ac84d2dfaead241cb1efbe4102e792ef2d8108e2e99b8442d21aR185-R187)
